def obtenerDicPaises():
  d = {
    'EUROPA': ['AUSTRIA', 'BELGICA', 'BULGARIA', 'CHIPRE', 'DINAMARCA', 'ESPAÑA', 'FINLANDIA', 'FRANCIA', 'GRECIA', 'HUNGRIA', 'IRLANDA', 'ITALIA', 'LUXEMBURGO', 'MALTA', 'PAISES BAJOS', 'POLONIA', 'PORTUGAL', 'REINO UNIDO', 'ALEMANIA', 'RUMANIA', 'SUECIA','LETONIA', 'ESTONIA', 'LITUANIA', 'REPUBLICA CHECA','REPUBLICA ESLOVACA', 'ESLOVENIA','ALBANIA', 'ISLANDIA','LIECHTENSTEIN','MONACO', 'NORUEGA', 'ANDORRA', 'SAN MARINO', 'SANTA SEDE', 'SUIZA', 'UCRANIA', 'MOLDAVIA', 'BELARUS', 'GEORGIA', 'BOSNIA Y HERZEGOVINA', 'CROACIA', 'ARMENIA', 'RUSIA', 'MACEDONIA ', 'SERBIA', 'MONTENEGRO', 'GUERNESEY', 'SVALBARD Y JAN MAYEN', 'ISLAS FEROE', 'ISLA DE MAN', 'GIBRALTAR', 'ISLAS DEL CANAL', 'JERSEY', 'ISLAS ALAND', 'TURQUIA'],
    
    'AFRICA': ['BURKINA FASO', 'ANGOLA', 'ARGELIA', 'BENIN', 'BOTSWANA', 'BURUNDI', 'CABO VERDE', 'CAMERUN', 'COMORES', 'CONGO', 'COSTA DE MARFIL', 'DJIBOUTI', 'EGIPTO', 'ETIOPIA', 'GABON', 'GAMBIA', 'GHANA', 'GUINEA', 'GUINEA-BISSAU', 'GUINEA ECUATORIAL', 'KENIA', 'LESOTHO', 'LIBERIA', 'LIBIA', 'MADAGASCAR', 'MALAWI', 'MALI', 'MARRUECOS', 'MAURICIO', 'MAURITANIA', 'MOZAMBIQUE', 'NAMIBIA', 'NIGER', 'NIGERIA', 'REPUBLICA CENTROAFRICANA', 'SUDAFRICA', 'RUANDA', 'SANTO TOME Y PRINCIPE', 'SENEGAL', 'SEYCHELLES', 'SIERRA LEONA', 'SOMALIA', 'SUDAN', 'SWAZILANDIA', 'TANZANIA', 'CHAD', 'TOGO', 'TUNEZ', 'UGANDA', 'REP.DEMOCRATICA DEL CONGO', 'ZAMBIA', 'ZIMBABWE', 'ERITREA', 'SANTA HELENA', 'REUNION', 'MAYOTTE', 'SAHARA OCCIDENTAL'],
    
    'AMERICA': ['CANADA', 'ESTADOS UNIDOS DE AMERICA', 'MEXICO', 'GROENLANDIA', 'ANTIGUA Y BARBUDA', 'BAHAMAS', 'BARBADOS', 'BELICE', 'COSTA RICA', 'CUBA', 'DOMINICA', 'EL SALVADOR', 'GRANADA', 'GUATEMALA', 'HAITI', 'HONDURAS', 'JAMAICA', 'NICARAGUA', 'PANAMA', 'SAN VICENTE Y LAS GRANADINAS', 'REPUBLICA DOMINICANA', 'TRINIDAD Y TOBAGO', 'SANTA LUCIA', 'SAN CRISTOBAL Y NIEVES', 'ARUBA', 'ANGUILLA', 'SAN BARTOLOME', 'MARTINICA', 'PUERTO RICO', 'BERMUDAS', 'ARGENTINA', 'BOLIVIA', 'BRASIL', 'COLOMBIA', 'CHILE', 'ECUADOR', 'GUYANA', 'PARAGUAY', 'PERU', 'SURINAM', 'URUGUAY', 'VENEZUELA', 'GUAYANA FRANCESA', 'ISLAS MALVINAS'],
    
    'ASIA': ['AFGANISTAN', 'ARABIA SAUDI', 'BAHREIN', 'BANGLADESH', 'MYANMAR', 'CHINA', 'EMIRATOS ARABES UNIDOS', 'FILIPINAS', 'INDIA', 'INDONESIA', 'IRAQ', 'IRAN', 'ISRAEL', 'JAPON', 'JORDANIA', 'CAMBOYA', 'KUWAIT', 'LAOS', 'LIBANO', 'MALASIA', 'MALDIVAS', 'MONGOLIA', 'NEPAL', 'OMAN', 'PAKISTAN', 'QATAR', 'COREA', 'COREA DEL NORTE ', 'SINGAPUR', 'SIRIA', 'SRI LANKA', 'TAILANDIA', 'VIETNAM', 'BRUNEI', 'ISLAS MARSHALL', 'YEMEN', 'AZERBAIYAN', 'KAZAJSTAN', 'KIRGUISTAN', 'TADYIKISTAN', 'TURKMENISTAN', 'UZBEKISTAN', 'ISLAS MARIANAS DEL NORTE', 'PALESTINA', 'HONG KONG', 'BHUTÁN', 'GUAM', 'MACAO'],
    
    'OCEANIA': ['AUSTRALIA', 'FIJI', 'NUEVA ZELANDA', 'PAPUA NUEVA GUINEA', 'ISLAS SALOMON', 'SAMOA', 'TONGA', 'VANUATU', 'MICRONESIA', 'TUVALU', 'NAURU', 'PALAOS', 'TIMOR ORIENTAL']
    }
  return d


